rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key
server:
  port: 8084
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: muratakbope.93@gmail.com
    password: nxhnarhdtnsnbrhf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydatabasename;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:mydatabasename
    user: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalStrategyNamingStrategyStandardImpl
